# see https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md
# and https://typeof.net/Iosevka/customizer :--)

[buildPlans.reid-mono]
family = "Reid Mono"
spacing = "normal"
serifs = "sans"
export-glyph-names = false

[buildPlans.reid-mono.ligations]
inherits = "default-calt"   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set

[buildPlans.reid-mono.weights.regular]
shape = 400
menu  = 400
css   = 400

# uncomment this to build a bold version!
[buildPlans.reid-mono.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.reid-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

# uncomment this to build an italic version!
# [buildPlans.reid-mono.slopes.italic]
# angle = 9.4
# shape = "italic"
# menu = "italic"
# css = "italic"

[buildPlans.reid-mono.widths.normal]
shape = 520 # default for Iosevka is 500 (fairly narrow)
menu  = 5
css   = "normal"

[buildPlans.reid-mono.variants]
inherits = "ss14" # JetBrains Mono-inspired presets

[buildPlans.reid-mono.variants.design]
capital-j = "serifless"
capital-w = "straight"
w = "straight"
one = "base"
zero = "slashed"
four = "closed"
paren = "normal"
brace = "straight"
ampersand = "closed"
question = "smooth"